apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: pf1jkol8x-nodejs 
  janus-idp.io/tekton: pf1jkol8x-nodejs
  backstage.io/kubernetes-id: pf1jkol8x-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: pf1jkol8x-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml