apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: pf1jkol8x-nodejs
  janus-idp.io/tekton: pf1jkol8x-nodejs
  backstage.io/kubernetes-id: pf1jkol8x-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: pf1jkol8x-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
